apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v8bqw0z7p-dotnet-basic
  janus-idp.io/tekton: v8bqw0z7p-dotnet-basic
  backstage.io/kubernetes-id: v8bqw0z7p-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v8bqw0z7p-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
